# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c64a71191f0ffa452d071b409b5b124d253092ebebd2f3faf2f495a40b343a97e59fc250fc513636b1a80cacf7502b85fb3a200460acc7a5e9a565ceed22793

test:
  secret_key_base: ea4be4cb2a1d27606b2b27f64d1b72c111dc9a03c14b76cec02653f5fb64023b1bbbf8bed8adf7c371e25c45fa7ca9f365c7fbab62368de29b48c72c90871d12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
